### ISSUE TITLE
Class 'yii\bootstrap\Html' not found

### ISSUE THREAD

**Issue by Vitaxxxa** [modernkernel/yii2-skeleton#2]
i have this error

> "Class 'yii\bootstrap\Html' not found"

after I installed according to the instructions 

> in /home/xxxx/public_html/xxxx/vendor/modernkernel/yii2-theme-adminlte/layouts/main.php at line 32

**Comment by harrytang** [comment]
make sure your composer.json has "yiisoft/yii2-bootstrap" in require section.
